# Not a C# project
build: off

matrix:
   - PYTHON: "C:\\Python37"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install -r requirements.txt"
  - pip install .

test_script:
  - python setup.py test